### ISSUE TITLE
user is not redirect to after  sign path on updating 2fa setting

### ISSUE THREAD

**Issue by aki1221** [williamatodd/devise-2fa#17] opened 2019-10-10 16:18 UTC
not sure if this a bug ? but once user has successfully set his 2fa setting he should be redirect to some page but currentlysetting page is shown and there is way to get out of it until you manually changes url.

**Comment by aki1221** [comment] 2019-10-10 16:20
@williamatodd

**Comment by williamatodd** [comment] 2019-10-10 18:54
@aki1221 I'll take a look at this tomorrow morning.

**Comment by williamatodd** [comment] 2019-10-11 15:43
@aki1221 are you saying that you're expecting a controller-level redirect that is not occurring?

This is intended behavior which can be overridden on a case-by-case basis by copying the controller to the application, see https://github.com/williamatodd/devise-2fa/blob/master/app/controllers/devise/tokens_controller.rb#L28

I'm going to close this as it's not a bug.  If you'd like to submit a pull request with an override function for redirects, I'll consider merging it if it's accompanied by robust test cases.

**Closed as completed by williamatodd** 2019-10-11 15:43 UTC
Labels: wontfix
